#%RAML 0.8
title: FGC API
version: FGC_VERSION
baseUri: http://localhost:9090/tradeserver
/services:
  /register:
    post:
      description: Register
      body:
        application/json:
          schema: !include schemas/register_request.schema
          example: |
            {"username":"leetcooper","email":"lee.cooper@firstglobalcredit.com","password":"F1stCr3d14@"}
      responses:
        200:
          headers:
            X-Content-Type-Options:
                type: string
            X-XSS-Protection:
                type: string
            X-Application-Context:
                type: string
          body:
            application/json:
              schema: !include schemas/register_response.schema
              example: |
                {"email":"lee.cooper@firstglobalcredit.com"}
        400:
          headers:
            X-Content-Type-Options:
                type: string
            X-XSS-Protection:
                type: string
            X-Application-Context:
                type: string
          body:
            application/json:
              schema: !include schemas/error.schema
              example: |
                {"errors":{"errors":[{"code":"UE01","systemMessage":"User exists already"}]}}